<a href="https://colab.research.google.com/github/PalakKumari/ML-Learn-small-proj/blob/master/Neural_net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x=np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]])
y=np.array([[1],[0],[1],[0]])

In [ ]:
x.shape

(4, 3)

In [ ]:
y.shape

(4, 1)

In [ ]:
#assign wt values
np.random.seed(1)
weights=np.random.random((3,1))
weights

array([[4.17022005e-01],
       [7.20324493e-01],
       [1.14374817e-04]])

In [ ]:
mul=np.dot(x,weights)+0.02
mul

array([[0.43713638],
       [0.02011437],
       [1.1573465 ],
       [0.74032449]])

In [ ]:
#create the activation function
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
sigmoid(0.6)

0.6456563062257954

In [ ]:
mul=np.dot(x,weights)+ 0.02
ypred=sigmoid(mul)
ypred

array([[0.60757648],
       [0.50502842],
       [0.76085023],
       [0.67706681]])

In [ ]:
ypred.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
def gradient(a,x):
  return a*x*(1-x)

In [ ]:
mul=np.dot(x,weights)+0.02
ypred=sigmoid(mul)
error=y-ypred
error

array([[ 0.39242352],
       [-0.50502842],
       [ 0.23914977],
       [-0.67706681]])

In [ ]:
mul=np.dot(x,weights)+0.02
ypred=sigmoid(mul)
error=y-ypred
change_int_weight=gradient(error,ypred)
weights=weights+np.dot(x.T,change_int_weight) #transpose
error

array([[ 0.39242352],
       [-0.50502842],
       [ 0.23914977],
       [-0.67706681]])

In [ ]:
#training 
for i in range(500):
  mul=np.dot(x,weights)+0.02
  ypred=sigmoid(mul)
  error=y-ypred
  change_int_weight=gradient(error,ypred)
  weights= weights+np.dot(x.T,change_int_weight)+0.02

In [ ]:
print('Error',error,'\n')
print(ypred,'\n')
print(ypred.round(),'\n')
print(weights,'\n')
print(x,'\n')
print(y,'\n')

Error [[ 1.20923241e-05]
 [-1.53730858e-01]
 [ 1.20923241e-05]
 [-1.53730859e-01]] 

[[0.99998791]
 [0.15373086]
 [0.99998791]
 [0.15373086]] 

[[1.]
 [0.]
 [1.]
 [0.]] 

[[13.04856163]
 [-1.72563407]
 [-1.72563407]] 

[[1 0 1]
 [0 0 1]
 [1 1 0]
 [0 1 0]] 

[[1]
 [0]
 [1]
 [0]] 



In [ ]:
new_data=np.array([[0,0,0],[1,0,0],[1,1,1]])
mul=np.dot(x,weights)+0.02
ypred=sigmoid(mul)
ypred.round()


array([[1.],
       [0.],
       [1.],
       [0.]])